"""create all tables

Revision ID: b19858da31b6
Revises: 
Create Date: 2026-03-11 00:32:47.397536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b19858da31b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cf_association_groupings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_association_groupings_tenant_identifier')
    )
    op.create_index('ix_cf_association_groupings_tenant_title', 'cf_association_groupings', ['tenant_id', 'title'], unique=False)
    op.create_table('cf_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('hierarchy_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_concepts_tenant_identifier')
    )
    op.create_index('ix_cf_concepts_tenant_title', 'cf_concepts', ['tenant_id', 'title'], unique=False)
    op.create_table('cf_item_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type_code', sa.String(), nullable=True),
    sa.Column('hierarchy_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_item_types_tenant_identifier')
    )
    op.create_index('ix_cf_item_types_tenant_title', 'cf_item_types', ['tenant_id', 'title'], unique=False)
    op.create_table('cf_licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('license_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_licenses_tenant_identifier')
    )
    op.create_index('ix_cf_licenses_tenant_title', 'cf_licenses', ['tenant_id', 'title'], unique=False)
    op.create_table('cf_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hierarchy_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_subjects_tenant_identifier')
    )
    op.create_index('ix_cf_subjects_tenant_title', 'cf_subjects', ['tenant_id', 'title'], unique=False)
    op.create_table('cf_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cf_license_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('framework_type', sa.String(), nullable=True),
    sa.Column('case_version', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('adoption_status', sa.String(), nullable=True),
    sa.Column('status_start_date', sa.Date(), nullable=True),
    sa.Column('status_end_date', sa.Date(), nullable=True),
    sa.Column('official_source_url', sa.String(), nullable=True),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject_uri', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_license_id'], ['cf_licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_documents_tenant_identifier')
    )
    op.create_table('cf_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cf_document_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('association_type', sa.String(), nullable=False),
    sa.Column('origin_node_uri', sa.String(), nullable=False),
    sa.Column('origin_node_identifier', sa.String(), nullable=False),
    sa.Column('origin_node_title', sa.String(), nullable=True),
    sa.Column('origin_node_target_type', sa.String(), nullable=True),
    sa.Column('destination_node_uri', sa.String(), nullable=False),
    sa.Column('destination_node_identifier', sa.String(), nullable=False),
    sa.Column('destination_node_title', sa.String(), nullable=True),
    sa.Column('destination_node_target_type', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('cf_association_grouping_id', sa.UUID(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_association_grouping_id'], ['cf_association_groupings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cf_document_id'], ['cf_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_associations_tenant_identifier')
    )
    op.create_index('ix_cf_associations_destination_node', 'cf_associations', ['destination_node_identifier'], unique=False)
    op.create_index('ix_cf_associations_document_destination', 'cf_associations', ['cf_document_id', 'destination_node_identifier'], unique=False)
    op.create_index('ix_cf_associations_origin_node', 'cf_associations', ['origin_node_identifier'], unique=False)
    op.create_table('cf_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cf_document_id', sa.UUID(), nullable=False),
    sa.Column('cf_item_type_id', sa.UUID(), nullable=True),
    sa.Column('cf_license_id', sa.UUID(), nullable=True),
    sa.Column('cf_concept_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('full_statement', sa.Text(), nullable=False),
    sa.Column('human_coding_scheme', sa.String(), nullable=True),
    sa.Column('list_enumeration', sa.String(), nullable=True),
    sa.Column('abbreviated_statement', sa.Text(), nullable=True),
    sa.Column('concept_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education_level', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject_uri', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status_start_date', sa.Date(), nullable=True),
    sa.Column('status_end_date', sa.Date(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_concept_id'], ['cf_concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cf_document_id'], ['cf_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cf_item_type_id'], ['cf_item_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cf_license_id'], ['cf_licenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_items_tenant_identifier')
    )
    op.create_index('ix_cf_items_document_depth', 'cf_items', ['cf_document_id', 'depth'], unique=False)
    op.create_index('ix_cf_items_tenant_document_coding', 'cf_items', ['tenant_id', 'cf_document_id', 'human_coding_scheme'], unique=False)
    op.create_table('cf_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cf_document_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_document_id'], ['cf_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cf_rubrics_tenant_identifier')
    )
    op.create_index('ix_cf_rubrics_document', 'cf_rubrics', ['cf_document_id'], unique=False)
    op.create_table('cf_rubric_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cf_rubric_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('cf_item_id', sa.UUID(), nullable=True),
    sa.Column('rubric_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('rubric_criterion_text_plain', sa.Text(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_item_id'], ['cf_items.id'], ),
    sa.ForeignKeyConstraint(['cf_rubric_id'], ['cf_rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='uq_cf_rubric_criteria_identifier')
    )
    op.create_index('ix_cf_rubric_criteria_identifier', 'cf_rubric_criteria', ['identifier'], unique=False)
    op.create_index('ix_cf_rubric_criteria_rubric', 'cf_rubric_criteria', ['cf_rubric_id'], unique=False)
    op.create_table('cf_rubric_criterion_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cf_rubric_criterion_id', sa.UUID(), nullable=False),
    sa.Column('rubric_criterion_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('last_change_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cf_rubric_criterion_id'], ['cf_rubric_criteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', name='uq_cf_rubric_criterion_levels_identifier')
    )
    op.create_index('ix_cf_rubric_criterion_levels_criterion', 'cf_rubric_criterion_levels', ['cf_rubric_criterion_id'], unique=False)
    op.create_index('ix_cf_rubric_criterion_levels_identifier', 'cf_rubric_criterion_levels', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cf_rubric_criterion_levels_identifier', table_name='cf_rubric_criterion_levels')
    op.drop_index('ix_cf_rubric_criterion_levels_criterion', table_name='cf_rubric_criterion_levels')
    op.drop_table('cf_rubric_criterion_levels')
    op.drop_index('ix_cf_rubric_criteria_rubric', table_name='cf_rubric_criteria')
    op.drop_index('ix_cf_rubric_criteria_identifier', table_name='cf_rubric_criteria')
    op.drop_table('cf_rubric_criteria')
    op.drop_index('ix_cf_rubrics_document', table_name='cf_rubrics')
    op.drop_table('cf_rubrics')
    op.drop_index('ix_cf_items_tenant_document_coding', table_name='cf_items')
    op.drop_index('ix_cf_items_document_depth', table_name='cf_items')
    op.drop_table('cf_items')
    op.drop_index('ix_cf_associations_origin_node', table_name='cf_associations')
    op.drop_index('ix_cf_associations_document_destination', table_name='cf_associations')
    op.drop_index('ix_cf_associations_destination_node', table_name='cf_associations')
    op.drop_table('cf_associations')
    op.drop_table('cf_documents')
    op.drop_index('ix_cf_subjects_tenant_title', table_name='cf_subjects')
    op.drop_table('cf_subjects')
    op.drop_index('ix_cf_licenses_tenant_title', table_name='cf_licenses')
    op.drop_table('cf_licenses')
    op.drop_index('ix_cf_item_types_tenant_title', table_name='cf_item_types')
    op.drop_table('cf_item_types')
    op.drop_index('ix_cf_concepts_tenant_title', table_name='cf_concepts')
    op.drop_table('cf_concepts')
    op.drop_index('ix_cf_association_groupings_tenant_title', table_name='cf_association_groupings')
    op.drop_table('cf_association_groupings')
    op.drop_table('tenants')
    # ### end Alembic commands ###
