"""add display_order to tenants and cf_documents

Revision ID: c704faa62b4f
Revises: 5389de18d5e7
Create Date: 2026-06-10 09:47:20.503917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c704faa62b4f'
down_revision: Union[str, None] = '5389de18d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cf_documents', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('display_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'display_order')
    op.drop_column('cf_documents', 'display_order')
    # ### end Alembic commands ###
